const PlayersApp=(()=>{let all=[],shown=[],key='fm',dir='desc';const s={q:'',role:'',team:'',listed:false};
const roles={P:'Portieri',D:'Difensori',C:'Centrocampisti',A:'Attaccanti'};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const num=v=>Number.isFinite(Number(v))?Number(v):0; const fmt=v=>{let n=num(v);return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')};
function badge(r){let c={P:'bg-amber-100 text-amber-800',D:'bg-sky-100 text-sky-800',C:'bg-emerald-100 text-emerald-800',A:'bg-rose-100 text-rose-800'}[r]||'bg-slate-100 text-slate-700';return `<span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${c}">${esc(r)}</span>`}
function filter(){let q=s.q.toLowerCase().trim();shown=all.filter(p=>(!q||p.name.toLowerCase().includes(q)||String(p.team).toLowerCase().includes(q))&&(!s.role||p.role===s.role)&&(!s.team||p.team===s.team)&&(!s.listed||!p.out_of_list));shown.sort((a,b)=>{let x=Number(a[key]),y=Number(b[key]);let c=Number.isFinite(x)&&Number.isFinite(y)?x-y:String(a[key]??'').localeCompare(String(b[key]??''));return dir==='asc'?c:-c});render()}
function render(){document.querySelector('#resultCount').textContent=`${shown.length} giocatori`;document.querySelector('#playersTableBody').innerHTML=shown.map((p,i)=>`<tr data-i="${i}" class="border-b border-slate-100 hover:bg-slate-50 cursor-pointer"><td class="px-4 py-3 font-semibold">${esc(p.name)}</td><td class="px-3">${badge(p.role)}</td><td class="px-3 text-slate-600">${esc(p.team)}</td><td class="px-3 text-right">${fmt(p.pgv)}</td><td class="px-3 text-right">${fmt(p.mv)}</td><td class="px-3 text-right font-semibold">${fmt(p.fm)}</td><td class="px-3 text-right">${fmt(p.fvm)}</td><td class="px-3 text-right">${fmt(p.quot)}</td><td class="px-3 text-center text-xs">${p.out_of_list?'Fuori':'OK'}</td></tr>`).join('');document.querySelector('#playersCards').innerHTML=shown.map((p,i)=>`<button data-i="${i}" class="w-full text-left rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="flex justify-between"><div><b>${esc(p.name)}</b><div class="text-sm text-slate-500">${esc(p.team)} · ${roles[p.role]||p.role}</div></div>${badge(p.role)}</div><div class="grid grid-cols-4 gap-2 mt-4 text-center text-xs"><div><b>${fmt(p.mv)}</b><small class="block text-slate-400">MV</small></div><div><b>${fmt(p.fm)}</b><small class="block text-slate-400">FM</small></div><div><b>${fmt(p.fvm)}</b><small class="block text-slate-400">FVM</small></div><div><b>${fmt(p.quot)}</b><small class="block text-slate-400">QUOT</small></div></div></button>`).join('');document.querySelectorAll('[data-i]').forEach(e=>e.onclick=()=>open(shown[+e.dataset.i]))}
function open(p){document.querySelector('#modalBody').innerHTML=`${badge(p.role)} ${p.out_of_list?'<span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-500">Fuori lista</span>':''}<h2 class="text-2xl font-black mt-3">${esc(p.name)}</h2><p class="text-slate-500">${esc(p.team)}</p><div class="grid grid-cols-2 sm:grid-cols-5 gap-3 mt-6">${[['PGv',p.pgv],['MV',p.mv],['FM',p.fm],['FVM',p.fvm],['QUOT',p.quot]].map(x=>`<div class="rounded-2xl bg-slate-50 p-4"><div class="text-xs text-slate-400 font-bold">${x[0]}</div><div class="text-xl font-black">${fmt(x[1])}</div></div>`).join('')}</div>`;document.querySelector('#modal').classList.remove('hidden');document.querySelector('#modal').classList.add('flex')}
function bind(){searchInput.oninput=e=>(s.q=e.target.value,filter());roleFilter.onchange=e=>(s.role=e.target.value,filter());teamFilter.onchange=e=>(s.team=e.target.value,filter());onlyListed.onchange=e=>(s.listed=e.target.checked,filter());resetFilters.onclick=()=>{s.q=s.role=s.team='';s.listed=false;searchInput.value='';roleFilter.value='';teamFilter.value='';onlyListed.checked=false;filter()};closeModal.onclick=()=>modal.classList.add('hidden');document.querySelectorAll('[data-sort]').forEach(e=>e.onclick=()=>{key=e.dataset.sort;dir=dir==='asc'?'desc':'asc';filter()})}
async function init(){all=await (await fetch('./data/players.json')).json();let teams=[...new Set(all.map(p=>p.team).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'it'));teamFilter.innerHTML='<option value="">Tutte le squadre</option>'+teams.map(t=>`<option>${esc(t)}</option>`).join('');bind();filter()}return{init}})();document.addEventListener('DOMContentLoaded',PlayersApp.init);
